# Generated by Django 4.0.4 on 2022-05-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_patient_waiting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
